CLI V2
replayableio/cli pull request #3
Opened 2022-09-09 23:02 UTC by ianjennings

[![Able to pipe a replay decription!](https://cdn.loom.com/sessions/thumbnails/b7236da2aa6d418488d281b86413a7c4-with-play.gif)](https://www.loom.com/share/b7236da2aa6d418488d281b86413a7c4)

  Watch [Able to pipe a replay decription!](https://www.loom.com/share/b7236da2aa6d418488d281b86413a7c4) on Replayable, umm wait, on Loom
  
  Depends on https://github.com/replayableio/desktop/pull/411

The readme will explain most of what's going on here:
https://github.com/replayableio/cli/blob/e752d9e1900382ff642c574514eddf1608bc477d/README.md

2022-10-04 22:43 UTC, ianjennings commented
Draft because I need to move from TCP to Websockets

2022-11-26 14:23 UTC, AyoubElk requested changes

2022-11-26 14:23 UTC, AyoubElk commented on lib.js
> +      console.log("Disconnected from replayable".notice);
`.notice` looks like a typo?

2022-11-26 14:23 UTC, AyoubElk commented on README.md
> +### Embed a logfile in the replay description
Missing example command.

2022-11-26 14:23 UTC, AyoubElk commented on lib.js
> +          "You may need to download and install the app from https://bit.ly/3erITXJ"
Link doesn't work
<img width="945" alt="image" src="https://user-images.githubusercontent.com/11050534/204093577-8a21fa7e-9075-4353-b566-91d516027772.png">

2022-11-30 02:52 UTC, ianjennings commented on lib.js
> +          "You may need to download and install the app from https://bit.ly/3erITXJ"
Great find.

2022-11-30 20:03 UTC, merged