docs: remove web and sdk info from readme
replayableio/cli pull request #5
Opened 2022-12-16 21:57 UTC by jasonribble

A clearer README to have a clear scope of this repo. Other examples are not in this repo, as far as I understand

2022-12-17 02:35 UTC, ianjennings requested changes

2022-12-17 02:35 UTC, ianjennings commented on README.md
> -
All NodeJS is within the scope of this package. NodeJS packages can be a CLI, frontend, or backend.

2022-12-17 02:35 UTC, ianjennings commented on README.md
> -```
This stuff is probably out of scope, but I don't want to remove it until we have a centralized place for it.

2022-12-27 22:58 UTC, jasonribble commented
Ah! I understand. I'll close this PR

2022-12-27 22:58 UTC, closed without merging